In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier  # Import KNeighborsClassifier


dataset = pd.read_csv("Social_Network_Ads.csv")


dataset = pd.get_dummies(dataset, drop_first=True)
dataset = dataset.drop("User ID", axis=1)


indep = dataset[["Age", "EstimatedSalary", "Gender_Male"]]
dep = dataset["Purchased"]


X_train, X_test, Y_train, Y_test = train_test_split(indep, dep, test_size=1/3, random_state=0)


algorithms = ['auto', 'ball_tree', 'kd_tree', 'brute']
for algo in algorithms:
    classifier = KNeighborsClassifier(n_neighbors=7, algorithm=algo, metric="minkowski", p=2)
    classifier.fit(X_train, Y_train)
    y_pred = classifier.predict(X_test)
    cm = confusion_matrix(Y_test, y_pred)
    cr = classification_report(Y_test, y_pred)
    print(f"Algorithm: {algo}")
    print("Confusion Matrix:")
    print(cm)
    print("Classification Report:")
    print(cr)
    print("\n")


Algorithm: auto
Confusion Matrix:
[[79  6]
 [16 33]]
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.93      0.88        85
           1       0.85      0.67      0.75        49

    accuracy                           0.84       134
   macro avg       0.84      0.80      0.81       134
weighted avg       0.84      0.84      0.83       134



Algorithm: ball_tree
Confusion Matrix:
[[79  6]
 [16 33]]
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.93      0.88        85
           1       0.85      0.67      0.75        49

    accuracy                           0.84       134
   macro avg       0.84      0.80      0.81       134
weighted avg       0.84      0.84      0.83       134



Algorithm: kd_tree
Confusion Matrix:
[[79  6]
 [16 33]]
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.93      0.88        

C:\Anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
C:\Anaconda\lib\site-packages\sklearn\linear_model\least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).ep